ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER Administrador IDENTIFIED BY Administrador;
GRANT CONNECT, RESOURCE TO Administrador;
GRANT DBA TO Administrador;
GRANT ALL PRIVILEGES TO Administrador;

CONNECT Administrador/Administrador;


CREATE TABLE ROLES (
    ID_ROL NUMBER PRIMARY KEY,
    NOMBRE_ROL VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200)
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA NUMBER PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200)
);

CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(15),
    ID_ROL NUMBER,
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID_ROL)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    PRECIO NUMBER(10, 2) NOT NULL,
    STOCK NUMBER NOT NULL,
    ID_CATEGORIA NUMBER,
    RUTA_IMAGEN VARCHAR2(255),
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO NUMBER PRIMARY KEY,
    FECHA DATE NOT NULL,
    ID_USUARIO NUMBER,
    PRECIO_UNITARIO NUMBER(10, 2) NOT NULL,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER NOT NULL,
    TOTAL NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_PEDIDOS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO),
    CONSTRAINT FK_PEDIDOS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);

CREATE TABLE FACTURAS (
    ID_FACTURA NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    ID_USUARIO NUMBER,
    FECHA_EMISION DATE NOT NULL,
    TOTAL NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_FACTURAS_PEDIDOS FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
    CONSTRAINT FK_FACTURAS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE SALARIO (
    ID_SALARIO NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER,
    MONTO NUMBER(10, 2) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    CONSTRAINT FK_SALARIO_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE INVENTARIO (
    ID_INVENTARIO NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER,
    CANTIDAD_DISPONIBLE NUMBER NOT NULL,
    CONSTRAINT FK_INVENTARIO_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);

CREATE TABLE TALLAS (
    ID_TALLA NUMBER PRIMARY KEY,
    TALLA VARCHAR2(10) NOT NULL
);

CREATE TABLE COLOR (
    ID_COLOR NUMBER PRIMARY KEY,
    COLOR VARCHAR2(50) NOT NULL
);

CREATE TABLE ROPA (
    ID_ROPA NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER,
    ID_TALLA NUMBER,
    ID_COLOR NUMBER,
    TIPO VARCHAR2(50),
    RUTA_IMAGEN VARCHAR2(255),
    CONSTRAINT FK_ROPA_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO),
    CONSTRAINT FK_ROPA_TALLAS FOREIGN KEY (ID_TALLA) REFERENCES TALLAS (ID_TALLA),
    CONSTRAINT FK_ROPA_COLOR FOREIGN KEY (ID_COLOR) REFERENCES COLOR (ID_COLOR)
);

